services:
  backstage:
    container_name: game-backstage
    build:
      context: ./../backstage
      dockerfile: Dockerfile
    links:
      - redis
      - mysql
    ports:
      - '8005:17001'

  minigame:
    container_name: game-minigame
    build:
      context: ./../minigame
      dockerfile: Dockerfile
    links:
      - redis
      - mysql
    ports:
      - '9005:17001'
    environment:
      APP_NAME: minigame

  redis:
    container_name: game-redis
    hostname: game-redis
    restart: always
    build:
      context: ./redis
      dockerfile: Dockerfile
    volumes:
      - /data/game_data/redis:/data
    environment:
      TZ: Asia/Shanghai

  mysql:
    container_name: game-mysql
    hostname: game-mysql
    restart: always
    build:
      context: ./mysql
      dockerfile: Dockerfile
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - /data/game_data/mysql/:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      TZ: Asia/Shanghai